M = {}

function M.getTransportPilotNames(mission, unitTypes)
    return {
        "Sochi Red Helos #001",
        "Sochi Red Helos #002",
        "Sochi Red Helos #003",
        "Sochi Red Helos #004",
        "Sochi Red Helos #005",
        "Sochi Red Helos #006",
        "Sochi Red Helos #007",
        "Sochi Red Helos #008",
        "Sochi Red Helos #009",
        "Sochi Red Helos #010",
        "Sochi Red Helos #011",
        "Sochi Red Helos #012",


        "Sochi Blue Helos #001",
        "Sochi Blue Helos #002",
        "Sochi Blue Helos #003",
        "Sochi Blue Helos #005",
        "Sochi Blue Helos #006",
        "Sochi Blue Helos #007",
        "Sochi Blue Helos #008",
        "Sochi Blue Helos #009",
        "Sochi Blue Helos #010",
        "Sochi Blue Helos #011",
        "Sochi Blue Helos #012",

        "Gudauta Red Helos #001",
        "Gudauta Red Helos #002",
        "Gudauta Red Helos #003",
        "Gudauta Red Helos #004",
        "Gudauta Red Helos #005",
        "Gudauta Red Helos #006",
        "Gudauta Red Helos #007",
        "Gudauta Red Helos #008",
        "Gudauta Red Helos #009",
        "Gudauta Red Helos #010",
        "Gudauta Red Helos #011",
        "Gudauta Red Helos #012",

        "Gudauta Blue Helos #001",
        "Gudauta Blue Helos #002",
        "Gudauta Blue Helos #003",
        "Gudauta Blue Helos #005",
        "Gudauta Blue Helos #006",
        "Gudauta Blue Helos #007",
        "Gudauta Blue Helos #008",
        "Gudauta Blue Helos #009",
        "Gudauta Blue Helos #010",
        "Gudauta Blue Helos #011",
        "Gudauta Blue Helos #012",


        "Sukumi Red Helos #001",
        "Sukumi Red Helos #002",
        "Sukumi Red Helos #003",
        "Sukumi Red Helos #004",
        "Sukumi Red Helos #005",
        "Sukumi Red Helos #006",
        "Sukumi Red Helos #007",
        "Sukumi Red Helos #008",
        "Sukumi Red Helos #009",
        "Sukumi Red Helos #010",
        "Sukumi Red Helos #011",
        "Sukumi Red Helos #012",

        "Sukumi Blue Helos #001",
        "Sukumi Blue Helos #002",
        "Sukumi Blue Helos #003",
        "Sukumi Blue Helos #004",
        "Sukumi Blue Helos #005",
        "Sukumi Blue Helos #006",
        "Sukumi Blue Helos #007",
        "Sukumi Blue Helos #008",
        "Sukumi Blue Helos #009",
        "Sukumi Blue Helos #010",
        "Sukumi Blue Helos #011",
        "Sukumi Blue Helos #012",

        "Kobuleti Red Helos #001",
        "Kobuleti Red Helos #002",
        "Kobuleti Red Helos #003",
        "Kobuleti Red Helos #004",
        "Kobuleti Red Helos #005",
        "Kobuleti Red Helos #006",
        "Kobuleti Red Helos #007",
        "Kobuleti Red Helos #008",
        "Kobuleti Red Helos #009",
        "Kobuleti Red Helos #010",
        "Kobuleti Red Helos #011",
        "Kobuleti Red Helos #012",


        "Kobuleti Blue Helos #001",
        "Kobuleti Blue Helos #002",
        "Kobuleti Blue Helos #003",
        "Kobuleti Blue Helos #005",
        "Kobuleti Blue Helos #006",
        "Kobuleti Blue Helos #007",
        "Kobuleti Blue Helos #008",
        "Kobuleti Blue Helos #009",
        "Kobuleti Blue Helos #010",
        "Kobuleti Blue Helos #011",
        "Kobuleti Blue Helos #012",


        "Kutaisi Red Helos #001",
        "Kutaisi Red Helos #002",
        "Kutaisi Red Helos #003",
        "Kutaisi Red Helos #004",
        "Kutaisi Red Helos #005",
        "Kutaisi Red Helos #006",
        "Kutaisi Red Helos #007",
        "Kutaisi Red Helos #008",
        "Kutaisi Red Helos #009",
        "Kutaisi Red Helos #010",
        "Kutaisi Red Helos #011",
        "Kutaisi Red Helos #012",


        "Kutaisi Blue Helos #001",
        "Kutaisi Blue Helos #002",
        "Kutaisi Blue Helos #003",
        "Kutaisi Blue Helos #005",
        "Kutaisi Blue Helos #006",
        "Kutaisi Blue Helos #007",
        "Kutaisi Blue Helos #008",
        "Kutaisi Blue Helos #009",
        "Kutaisi Blue Helos #010",
        "Kutaisi Blue Helos #011",
        "Kutaisi Blue Helos #012",


        "Senaki Red Helos #001",
        "Senaki Red Helos #002",
        "Senaki Red Helos #003",
        "Senaki Red Helos #004",
        "Senaki Red Helos #005",
        "Senaki Red Helos #006",
        "Senaki Red Helos #007",
        "Senaki Red Helos #008",
        "Senaki Red Helos #009",
        "Senaki Red Helos #010",
        "Senaki Red Helos #011",
        "Senaki Red Helos #012",


        "Senaki Blue Helos #001",
        "Senaki Blue Helos #002",
        "Senaki Blue Helos #003",
        "Senaki Blue Helos #005",
        "Senaki Blue Helos #006",
        "Senaki Blue Helos #007",
        "Senaki Blue Helos #008",
        "Senaki Blue Helos #009",
        "Senaki Blue Helos #010",
        "Senaki Blue Helos #011",
        "Senaki Blue Helos #012",

        "GH05 BLUE HELOS #001",
        "GH05 BLUE HELOS #002",
        "GH05 BLUE HELOS #003",
        "GH05 BLUE HELOS #004",
        "GH05 BLUE HELOS #005",
        "GH05 BLUE HELOS #006",
        "GH05 BLUE HELOS #007",
        "GH05 BLUE HELOS #008",
        "GH05 BLUE HELOS #009",
        "GH05 BLUE HELOS #010",
        "GH05 BLUE HELOS #011",
        "GH05 BLUE HELOS #012",


        "GH05 RED HELOS #001",
        "GH05 RED HELOS #002",
        "GH05 RED HELOS #003",
        "GH05 RED HELOS #005",
        "GH05 RED HELOS #006",
        "GH05 RED HELOS #007",
        "GH05 RED HELOS #008",
        "GH05 RED HELOS #009",
        "GH05 RED HELOS #010",
        "GH05 RED HELOS #011",
        "GH05 RED HELOS #012",

        "KN61 BLUE HELOS #001",
        "KN61 BLUE HELOS #002",
        "KN61 BLUE HELOS #003",
        "KN61 BLUE HELOS #004",
        "KN61 BLUE HELOS #005",
        "KN61 BLUE HELOS #006",
        "KN61 BLUE HELOS #007",
        "KN61 BLUE HELOS #008",
        "KN61 BLUE HELOS #009",
        "KN61 BLUE HELOS #010",
        "KN61 BLUE HELOS #011",
        "KN61 BLUE HELOS #012",


        "KN61 RED HELOS #001",
        "KN61 RED HELOS #002",
        "KN61 RED HELOS #003",
        "KN61 RED HELOS #005",
        "KN61 RED HELOS #006",
        "KN61 RED HELOS #007",
        "KN61 RED HELOS #008",
        "KN61 RED HELOS #009",
        "KN61 RED HELOS #010",
        "KN61 RED HELOS #011",
        "KN61 RED HELOS #012",

        "ZENI BLUE HELOS #001",
        "ZENI BLUE HELOS #002",
        "ZENI BLUE HELOS #003",
        "ZENI BLUE HELOS #004",
        "ZENI BLUE HELOS #005",
        "ZENI BLUE HELOS #006",
        "ZENI BLUE HELOS #007",
        "ZENI BLUE HELOS #008",

        "ZENI RED HELOS #001",
        "ZENI RED HELOS #002",
        "ZENI RED HELOS #003",
        "ZENI RED HELOS #004",
        "ZENI RED HELOS #005",
        "ZENI RED HELOS #006",
        "ZENI RED HELOS #007",
        "ZENI RED HELOS #008",

        "RIKE BLUE HELOS #001",
        "RIKE BLUE HELOS #002",
        "RIKE BLUE HELOS #003",
        "RIKE BLUE HELOS #004",
        "RIKE BLUE HELOS #005",
        "RIKE BLUE HELOS #006",
        "RIKE BLUE HELOS #007",
        "RIKE BLUE HELOS #008",

        "RIKE RED HELOS #001",
        "RIKE RED HELOS #002",
        "RIKE RED HELOS #003",
        "RIKE RED HELOS #004",
        "RIKE RED HELOS #005",
        "RIKE RED HELOS #006",
        "RIKE RED HELOS #007",
        "RIKE RED HELOS #008",


        "Kutaisi Red AF #005",
        "Kutaisi Red AF #006",
        "Kobuleti Red AF #001",
        "Kobuleti Red AF #002",
        "Sukumi Blue AF #002",
        "Sukumi Blue AF #001",

        "heli1",

        -- *** AI transports names (different names only to ease identification in mission) ***

        -- Use any of the predefined names or set your own ones

        "transport1",
        "transport2",
        "transport3",
        "transport4",
        "transport5",
        "transport6",
        "transport7",
        "transport8",
        "transport9",
        "transport10",
    }
end

return M